spring:
  profiles:
    active: local # 기본 환경 선택
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true

# local 환경
---
spring:
  profiles: local
  datasource:
    data: classpath:data-h2.sql # 시작할때 실행시킬 script
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
    properties:
      hibernate.format_sql: true
  h2:
    console:
      enabled: true

# 운영 환경
---
spring.profiles: set1
spring.profiles.include: real-db

server:
  port: 8081

---
spring.profiles: set2
spring.profiles.include: real-db

server:
  port: 8082

---
spring:
  profiles: real-db
  datasource:
        url: jdbc:mariadb://database-1.cc1j8x3t3gto.ap-northeast-2.rds.amazonaws.com:3306/zzm
        username: khj
        password: ikeacafe!
        driver-class-name: org.mariadb.jdbc.Driver
